### ISSUE TITLE
Issues when Testing the M3 Interface

### ISSUE THREAD

**Issue by jordijoangimenez** [5G-MAG/rt-5gms-application-function#46]
Following the following documentation works: [local user building and installation](https://github.com/5G-MAG/rt-5gms-application-function/wiki/Testing-as-a-Local-User).

However "Testing Simple HTTP Configuration" and "HTTPS Configuration" fails with a "connection refused" to localhost:7777

```
fivegmag@NUC1:~/rt-5gms-application-function$ ~/rt-5gms-application-function/install/bin/open5gs-msafd -c ~/rt-5gms-application-function/examples/Test_http_canonical-msaf.yaml
Open5GS daemon v2.4.9-128-gf1c0b6d+

02/14 16:08:39.617: [app] INFO: Configuration: '/home/fivegmag/rt-5gms-application-function/examples/Test_http_canonical-msaf.yaml' (../subprojects/open5gs/lib/app/ogs-init.c:126)
02/14 16:08:39.618: [sbi] INFO: mhd_server() [0.0.0.0]:7778 (../subprojects/open5gs/lib/sbi/mhd-server.c:279)
02/14 16:08:39.619: [msaf] DEBUG: msaf_state_initial(): INIT (../src/5gmsaf/msaf-sm.c:20)
02/14 16:08:39.619: [msaf] DEBUG: msaf_state_functional(): ENTRY (../src/5gmsaf/msaf-sm.c:47)
02/14 16:08:39.619: [msaf] INFO: [766c63d6-ac79-41ed-954d-5357052a43bb] MSAF Running (../src/5gmsaf/msaf-sm.c:53)
02/14 16:08:39.619: [app] INFO: 5GMSAF initialize...done (../src/5gmsaf/app.c:24)
02/14 16:08:39.619: [msaf] DEBUG: BigBuckBunny_4s_onDemand_2014_05_09.mpd matches the regular expression
 (../src/5gmsaf/provisioning-session.c:581)
02/14 16:08:39.619: [msaf] DEBUG: Distribution URL: http://localhost/m4d/provisioning-session-766c6b6a-ac79-41ed-954d-5357052a43bb/ (../src/5gmsaf/provisioning-session.c:529)
02/14 16:08:39.619: [msaf] DEBUG: M3 client: Sending GET method to Application Server [localhost] to request the list of known certificates (../src/5gmsaf/application-server-context.c:151)
02/14 16:08:39.619: [msaf] INFO: Provisioning session = 766c6b6a-ac79-41ed-954d-5357052a43bb (../src/5gmsaf/msaf-sm.c:57)
02/14 16:08:39.619: [sbi] WARNING: [7] Failed to connect to localhost port 7777 after 0 ms: Connection refused (../subprojects/open5gs/lib/sbi/client.c:595)
02/14 16:08:39.619: [msaf] WARNING: client_notify_cb() failed [-1] (../src/5gmsaf/application-server-context.c:377)
```

**Comment by jordijoangimenez** [comment]
AS seem not to be running

**Comment by jordijoangimenez** [comment]
when, running the AS, how to run it? which -c CONFIG to use?

**Comment by jordijoangimenez** [comment]
Basically, the AS without -c CONFIG uses '/tmp/rt_5gms_as.conf' by default but this was created as root?

**Comment by davidjwbbc** [comment]
I should probably make the nginx configuration file (`/tmp/rt_5gms_as.conf`) a configuration file variable (not sure why it was overlooked and remains the only hardcoded setting).

**Comment by jordijoangimenez** [comment]
Looks like after fixing, there's a similar issue with the logs:
```
fivegmag@NUC1:~/rt-5gms-application-server$ 5gms-application-server
Traceback (most recent call last):
  File "/home/fivegmag/.local/bin/5gms-application-server", line 8, in <module>
    sys.exit(main())
  File "/home/fivegmag/.local/lib/python3.10/site-packages/rt_5gms_as/app.py", line 257, in main
    context = Context(config)
  File "/home/fivegmag/.local/lib/python3.10/site-packages/rt_5gms_as/context.py", line 87, in __init__
    self.__loadConfiguration(force=True)
  File "/home/fivegmag/.local/lib/python3.10/site-packages/rt_5gms_as/context.py", line 374, in __loadConfiguration
    os.makedirs(directory)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/log/rt-5gms'

```

**Comment by jordijoangimenez** [comment]
I've launched with the venv. Getting there:
AS is reporting this:
```
fivegmag@NUC1:~/rt-5gms-application-server$ venv/bin/5gms-application-server -c local-dev.conf
[2023-02-14 18:38:13 +0100] [79219] [INFO] Running on http://127.0.0.1:7777 (CTRL + C to quit)
INFO:hypercorn.error:Running on http://127.0.0.1:7777 (CTRL + C to quit)
INFO:rt-5gms-as:Getting list of certificates...
[2023-02-14 18:38:41 +0100] [79219] [INFO] 127.0.0.1:35396 - - [14/Feb/2023:18:38:41 +0100] "GET /3gpp-m3/v1/certificates 2" 200 223 "-" "-"
INFO:rt-5gms-as:Getting list of content hosting configurations...
[2023-02-14 18:38:41 +0100] [79219] [INFO] 127.0.0.1:35396 - - [14/Feb/2023:18:38:41 +0100] "GET /3gpp-m3/v1/content-hosting-configurations 2" 200 2 "-" "-"
DEBUG:rt-5gms-as:Context.haveCertificate('6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1') = False
INFO:rt-5gms-as:Adding certificate 6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1...
[2023-02-14 18:38:41 +0100] [79219] [INFO] 127.0.0.1:35400 - - [14/Feb/2023:18:38:41 +0100] "POST /3gpp-m3/v1/certificates/6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1 2" 201 0 "-" "-"
INFO:rt-5gms-as:Adding content hosting configuration 6bee641c-ac8e-41ed-be2d-c97dd5772aa7...
DEBUG:rt-5gms-as:Context.haveCertificate('6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1') = True
DEBUG:rt-5gms-as:CHC passed verification, checking for update: force=True, new hash=-5995845137847779547, old hash=None
INFO:rt-5gms-as:Reloading proxy daemon...
DEBUG:rt-5gms-as:Context.getCertificateFilename('6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1')
DEBUG:rt-5gms-as:Context.haveCertificate('6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1') = True
[2023-02-14 18:38:41 +0100] [79219] [INFO] 127.0.0.1:35400 - - [14/Feb/2023:18:38:41 +0100] "POST /3gpp-m3/v1/content-hosting-configurations/6bee641c-ac8e-41ed-be2d-c97dd5772aa7 2" 201 0 "-" "-"
```
when configured with:
```
fivegmag@NUC1:~/rt-5gms-application-function$ ~/rt-5gms-application-function/install/bin/open5gs-msafd -c ~/rt-5gms-application-function/examples/Test_https_canonical-msaf.yaml
Open5GS daemon v2.4.9-128-gf1c0b6d+

02/14 18:38:41.445: [app] INFO: Configuration: '/home/fivegmag/rt-5gms-application-function/examples/Test_https_canonical-msaf.yaml' (../subprojects/open5gs/lib/app/ogs-init.c:126)
02/14 18:38:41.447: [sbi] INFO: mhd_server() [0.0.0.0]:7778 (../subprojects/open5gs/lib/sbi/mhd-server.c:279)
02/14 18:38:41.447: [msaf] DEBUG: msaf_state_initial(): INIT (../src/5gmsaf/msaf-sm.c:20)
02/14 18:38:41.447: [msaf] DEBUG: msaf_state_functional(): ENTRY (../src/5gmsaf/msaf-sm.c:47)
02/14 18:38:41.447: [msaf] INFO: [6bee5c92-ac8e-41ed-be2d-c97dd5772aa7] MSAF Running (../src/5gmsaf/msaf-sm.c:53)
02/14 18:38:41.447: [app] INFO: 5GMSAF initialize...done (../src/5gmsaf/app.c:24)
02/14 18:38:41.447: [msaf] DEBUG: BigBuckBunny_4s_onDemand_2014_05_09.mpd matches the regular expression
 (../src/5gmsaf/provisioning-session.c:581)
02/14 18:38:41.447: [msaf] DEBUG: Distribution URL: http://localhost/m4d/provisioning-session-6bee641c-ac8e-41ed-be2d-c97dd5772aa7/ (../src/5gmsaf/provisioning-session.c:529)
02/14 18:38:41.447: [msaf] DEBUG: Distribution URL: https://localhost/m4d/provisioning-session-6bee641c-ac8e-41ed-be2d-c97dd5772aa7/ (../src/5gmsaf/provisioning-session.c:529)
02/14 18:38:41.447: [msaf] DEBUG: M3 client: Sending GET method to Application Server [localhost] to request the list of known certificates (../src/5gmsaf/application-server-context.c:151)
02/14 18:38:41.447: [msaf] INFO: Provisioning session = 6bee641c-ac8e-41ed-be2d-c97dd5772aa7 (../src/5gmsaf/msaf-sm.c:57)
02/14 18:38:41.490: [msaf] DEBUG: msaf_state_functional(): OGS_EVENT_NAME_SBI_CLIENT (../src/5gmsaf/msaf-sm.c:47)
02/14 18:38:41.490: [msaf] DEBUG: [certificates] Method [GET] with Response [200] received (../src/5gmsaf/msaf-sm.c:1111)
02/14 18:38:41.490: [msaf] DEBUG: Adding certificate [44b60742-ac8e-41ed-8355-e3798e100779:testcert1] to Current certificates (../src/5gmsaf/msaf-sm.c:1139)
02/14 18:38:41.490: [msaf] DEBUG: Adding certificate [3ad35dc6-ac8c-41ed-8b7f-c16728878a1b:testcert1] to Current certificates (../src/5gmsaf/msaf-sm.c:1139)
02/14 18:38:41.490: [msaf] DEBUG: Adding certificate [a82d7f14-ac8c-41ed-aa15-d75a49d5ff04:testcert1] to Current certificates (../src/5gmsaf/msaf-sm.c:1139)
02/14 18:38:41.490: [msaf] DEBUG: M3 client: Sending GET method to Application Server [localhost] to request the list of known content-hosting-configurations (../src/5gmsaf/application-server-context.c:154)
02/14 18:38:41.493: [msaf] DEBUG: msaf_state_functional(): OGS_EVENT_NAME_SBI_CLIENT (../src/5gmsaf/msaf-sm.c:47)
02/14 18:38:41.493: [msaf] DEBUG: [content-hosting-configurations] Method [GET] with Response [200] for Content Hosting Configuration operation [(null)] (../src/5gmsaf/msaf-sm.c:888)
02/14 18:38:41.493: [msaf] DEBUG: M3 client: Sending POST method to Application Server [localhost]for Certificate: [6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1] (../src/5gmsaf/application-server-context.c:187)
02/14 18:38:41.542: [msaf] DEBUG: msaf_state_functional(): OGS_EVENT_NAME_SBI_CLIENT (../src/5gmsaf/msaf-sm.c:47)
02/14 18:38:41.542: [msaf] DEBUG: [certificates] Method [POST] with Response [201] recieved for certificate [6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1] (../src/5gmsaf/msaf-sm.c:947)
02/14 18:38:41.542: [msaf] DEBUG: Removing certificate [6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1] from upload_certificates (../src/5gmsaf/msaf-sm.c:958)
02/14 18:38:41.542: [msaf] DEBUG: Adding certificate [6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1] to  current_certificates (../src/5gmsaf/msaf-sm.c:962)
02/14 18:38:41.542: [msaf] DEBUG: af_unique_cert_id: 6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1 (../src/5gmsaf/provisioning-session.c:47)
02/14 18:38:41.542: [msaf] DEBUG: dist_config->certificate_id: 6bee641c-ac8e-41ed-be2d-c97dd5772aa7:testcert1 (../src/5gmsaf/provisioning-session.c:50)
02/14 18:38:41.542: [msaf] DEBUG: M3 client: Sending POST method to Application Server [localhost] for Content Hosting Configuration:  [6bee641c-ac8e-41ed-be2d-c97dd5772aa7] (../src/5gmsaf/application-server-context.c:235)
02/14 18:38:41.642: [msaf] DEBUG: msaf_state_functional(): OGS_EVENT_NAME_SBI_CLIENT (../src/5gmsaf/msaf-sm.c:47)
02/14 18:38:41.642: [msaf] DEBUG: [content-hosting-configurations] Method [POST] with Response [201] recieved for Content Hosting Configuration [6bee641c-ac8e-41ed-be2d-c97dd5772aa7] (../src/5gmsaf/msaf-sm.c:736)
02/14 18:38:41.642: [msaf] DEBUG: Removing 6bee641c-ac8e-41ed-be2d-c97dd5772aa7 from upload_content_hosting_configurations (../src/5gmsaf/msaf-sm.c:745)
02/14 18:38:41.642: [msaf] DEBUG: Adding 6bee641c-ac8e-41ed-be2d-c97dd5772aa7 to current_content_hosting_configurations (../src/5gmsaf/msaf-sm.c:747)
```

However:
```
fivegmag@NUC1:~$ curl --cacert ~rt-5gms-application-function/examples/certificate-1.pem -v https://localhost:7777/m4d/provisioning-session-6bee641c-ac8e-41ed-be2d-c97dd5772aa7/BigBuckBunny_4s_onDemand_2014_05_09.mpd
*   Trying 127.0.0.1:7777...
* Connected to localhost (127.0.0.1) port 7777 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* error setting certificate file: ~rt-5gms-application-function/examples/certificate-1.pem
* Closing connection 0
curl: (77) error setting certificate file: ~rt-5gms-application-function/examples/certificate-1.pem

```

**Comment by rjb1000** [comment]
> curl --cacert ~rt-5gms-application-function/examples/certificate-1.pem -v https://localhost:7777/m4d/provisioning-session-6bee641c-ac8e-41ed-be2d-c97dd5772aa7/BigBuckBunny_4s_onDemand_2014_05_09.mpd
> error setting certificate file: ~rt-5gms-application-function/examples/certificate-1.pem

That looks like a local error from `curl`. Check your path to the PEM certificate file. It doesn't look valid. Did you mean `~/rt-5gms-application-function/examples/certificate-1.pem`?

**Comment by jordijoangimenez** [comment]
Let's go. @davidjwbbc, please correct the example command in "Test with HTTPS" 4.ix, the path should be ~/rt... and no ~rt... the URL without specifying port will not work, perhaps also add in the example command the localhost:7777?

**Comment by jordijoangimenez** [comment]
Launching after the check from Richard I get now the following:
```
fivegmag@NUC1:~$ curl --cacert ~/rt-5gms-application-function/examples/certificate-1.pem -v https://localhost:7777/m4d/provisioning-session-54bd3c7e-ad05-41ed-9ef3-db9681c7bb29/BigBuckBunny_4s_onDemand_2014_05_09.mpd
*   Trying 127.0.0.1:7777...
* Connected to localhost (127.0.0.1) port 7777 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /home/fivegmag/rt-5gms-application-function/examples/certificate-1.pem
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* (5454) (IN), , Unknown (72):
* error:0A00010B:SSL routines::wrong version number
* Closing connection 0
curl: (35) error:0A00010B:SSL routines::wrong version number

```

**Comment by davidjwbbc** [comment]
It would use port 8080 if you've followed the venv instructions for the AS, i.e. the command would be `curl --cacert ~/rt-5gms-application-function/examples/certificate-1.pem -v https://localhost:8080/m4d/provisioning-session-54bd3c7e-ad05-41ed-9ef3-db9681c7bb29/BigBuckBunny_4s_onDemand_2014_05_09.mpd`.

**Comment by davidjwbbc** [comment]
I've updated the instructions in the "[Testing the M3 interface](https://github.com/5G-MAG/rt-5gms-application-function/wiki/Testing-the-M3-Interface)" wiki page to add a link to running the AS as a local user for testing and to note that the port number needs to change to port 8443 is running the AS as a local user.

**Comment by jordijoangimenez** [comment]
I see now the MPD printed on the terminal! Excellent. Works! (apologies for not having spotted the right port).

I believe the only thing pending on this issue is when running the AS here and the access to the folders with root ownership: https://github.com/5G-MAG/rt-5gms-application-function/issues/46#issuecomment-1430064741

**Comment by dsilhavy** [comment]
@jordijoangimenez This is still an issue or can we close this?

**Comment by jordijoangimenez** [comment]
I believe we can close, Daniel.
